(define (make-point x y)
 	(cons x y))
(define (x-point p)
 	(car p))
(define (y-point p)
 	(cdr p))

(define (make-segment x1 y1 x2 y2)
 	 (let ((sp (make-point x1 y1))
		   (ep (make-point x2 y2)))
	  	  (cons sp ep)))

(define (start-segment seg)
 	(car seg))
(define (end-segment seg)
 	(cdr seg))

(define (print-point p)
 	(newline)
	(display "(")
	(display (x-point p))
	(display ",")
	(display (y-point p))
	(display ")"))

(define (midpoint-segment seg)
	(define (average x y) (/ (+ x y) 2))
	(let ((mp (cons (average (x-point (start-segment seg)) (x-point (end-segment seg))) 
			        (average (y-point (start-segment seg)) (y-point (end-segment seg))))))
	 	(print-point mp)))
(midpoint-segment (make-segment 1 5 2 4))
